### ISSUE TITLE
Hover over text

### ISSUE THREAD

**Issue by AverageMarcus** [danielthepope/xkcdfull#1]
Should be able to show the hover text some how. Maybe as a semi-transparent text box at the bottom?

**Comment by danielthepope** [comment]
It's almost as if you read the commented out bit in `index.handlebars` 😉 
If you could have the mouseover text underneath the comic and the title at the top, fitting the comic in all the remaining space that would be awesome!
i.e. not drawing anything over the comic

**Comment by AverageMarcus** [comment]
Flexbox?

**Comment by danielthepope** [comment]
#3 has fixed this. Thanks Marcus!
